version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.11.11
    steps:
      - checkout
      - run:
          name: plan
          command: |
            terraform init
            terraform plan
  apply:
    docker:
      - image: hashicorp/terraform:0.11.11
    steps:
      - checkout
      - run:
          name: apply
          command: |
            terraform init
            terraform apply -auto-approve
workflows:
  version: 2
  plan_apply:
    jobs:
      - plan
      - apply
          requires:
            - plan
          filters:
            branches:
              only:
                - master
